#!/usr/bin/env bash
set -ex

# Setup alias and environment variables
mkdir -p /home/duet # Will become HOME and WORKDIR
touch /home/duet/.bashrc
{
    echo 'alias ls="ls --color=auto"'
    echo 'alias ll="ls -hla"'
    echo 'export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]duet:\[\033[33;1m\]\w\[\033[m\]$ "' # Prettify prompt
} >> /home/duet/.bashrc

# Install and setup conda
curl -O https://repo.anaconda.com/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh
sh Miniconda3-4.6.14-Linux-x86_64.sh -b -p /miniconda3
rm -rf Miniconda3-4.6.14-Linux-x86_64.sh
export PATH=$PATH:/miniconda3/bin

# Update conda
conda update -n base -c defaults conda
conda config --set auto_activate_base false

# Install Duet
conda config --add channels bioconda && conda config --add channels conda-forge
conda create -n duet -y -c bioconda duet

# Add to PATH with conda activation
touch /usr/local/bin/run_duet
chmod 755 /usr/local/bin/run_duet
echo -e '#!/bin/bash\nsource /home/duet/.bashrc\neval "$(conda shell.bash hook)"\nconda activate duet\n\nduet $@\n' > /usr/local/bin/run_duet

